# Config file for Air
[build]
cmd = "templ generate && go build -o ./tmp/main ./cmd"
bin = "./tmp/main"
full_bin = "APP_ENV=dev ./tmp/main"
include_ext = ["go", "templ"]
exclude_dir = ["static", "node_modules"]
exclude_regex = ["_templ\\.go"]

[proxy]
  enabled = true
  proxy_port = 42069
  app_port = 8080